function createMenubar(app)
    % Creates the menubar

    app.m_file = uimenu(app.fig, "Text", "File");
    app.m_file_new = uimenu(app.m_file, "Text", "New Project...", "Accelerator", "N", ...
        "MenuSelectedFcn", createCallbackFcn(app, @cb_New), ...
        "Tooltip", app.tooltips.m_new);
    app.m_file_open = uimenu(app.m_file, "Text", "Open Project...", "Accelerator", "O", ...
        "MenuSelectedFcn", createCallbackFcn(app, @cb_Open), ...
        "Tooltip", app.tooltips.m_open);
    app.m_file_save = uimenu(app.m_file, "Text", "Save", "Accelerator", "S", ...
        "MenuSelectedFcn", createCallbackFcn(app, @cb_save), "Enable", "off", ...
        "Tooltip", app.tooltips.m_save);
    app.m_file_saveas = uimenu(app.m_file, "Text", "Save as...", ...
        "MenuSelectedFcn", createCallbackFcn(app, @cb_saveas), "Enable", "off", ...
        "Tooltip", app.tooltips.m_saveas);
    app.m_file_enableAutoSave = uimenu(app.m_file, "Text", "Enable Autosave", ...
        "MenuSelectedFcn", createCallbackFcn(app, @cb_AutosaveEnable), "Checked","on", "Enable", "off", ...
        "Tooltip", app.tooltips.m_enableAutosave,...
        "Separator", "on");

    app.m_edit = uimenu(app.fig, "Text", "Edit");
    app.m_edit_classlist = uimenu(app.m_edit, "Text", "Class List...", ...
        "MenuSelectedFcn", createCallbackFcn(app, @cb_changeClassList), ...
        "Tooltip", app.tooltips.m_edit_classlist, "enable", "off");
    app.m_edit_usersettings = uimenu(app.m_edit, "Text", "User Settings...",...
        "MenuSelectedFcn", createCallbackFcn(app, @cb_changeSettings));

    app.m_view = uimenu(app.fig, "Text", "View", "Enable","off");
    app.m_view_sort = uimenu(app.m_view, "Text", "Sort Students");
    app.m_view_sort_firstascend = uimenu(app.m_view_sort, "Text", "First Name A to Z", ...
        "UserData", ["FirstName","ascend"], "MenuSelectedFcn", createCallbackFcn(app, @cb_sortStudents, true), ...
        "Tooltip", "");
    app.m_view_sort_firstdescend = uimenu(app.m_view_sort, "Text", "First Name Z to A", ...
        "UserData", ["FirstName","descend"], "MenuSelectedFcn", createCallbackFcn(app, @cb_sortStudents, true), ...
        "Tooltip", "");
    app.m_view_sort_lastascend = uimenu(app.m_view_sort, "Text", "Last Name A to Z", ...
        "UserData", ["LastName","ascend"], "MenuSelectedFcn", createCallbackFcn(app, @cb_sortStudents, true), ...
        "Tooltip", "");
    app.m_view_sort_lastdescend = uimenu(app.m_view_sort, "Text", "Last Name Z to A", ...
        "UserData", ["LastName","descend"], "MenuSelectedFcn", createCallbackFcn(app, @cb_sortStudents, true), ...
        "Tooltip", "");
    app.m_view_increaseItem = uimenu(app.m_view, "Text", "Increase Criteria Fontsize", "Accelerator", "X", ...
        "UserData", 1, "MenuSelectedFcn", createCallbackFcn(app, @cb_changeItemSize, true), ...
        "Tooltip", app.tooltips.m_IncreaseItem);
    app.m_view_decreaseItem = uimenu(app.m_view, "Text", "Decrease Criteria Fontsize", "Accelerator", "Z", ...
        "UserData", -1, "MenuSelectedFcn", createCallbackFcn(app, @cb_changeItemSize, true), ...
        "Tooltip", app.tooltips.m_DecreaseItem);

    app.m_reports = uimenu(app.fig, "Text", "Reports", "Enable", "off");
    app.m_reports_class = uimenu(app.m_reports, "Text", "Classwide", ...
        "MenuSelectedFcn", createCallbackFcn(app, @cb_reportClass), ...
        "Tooltip", app.tooltips.m_classwide);

    app.m_export = uimenu(app.fig, "Text", "Export", "Enable", "off");
    app.m_export_stu = uimenu(app.m_export, "Text", "This student...", ...
        "MenuSelectedFcn", createCallbackFcn(app, @cb_ExportStudent), ...
        "Tooltip", app.tooltips.m_exportStudent,"Separator", "off");
    app.m_export_clipboard = uimenu(app.m_export, "Text", "This student to clipboard", ...
        "MenuSelectedFcn", createCallbackFcn(app, @cb_ExportStudentClipboard), ...
        "Tooltip", app.tooltips.m_exportStudent,"Separator", "on");
    app.m_export_markdown_clipboard = uimenu(app.m_export, "Text", "This student to clipboard (Markdown)", ...
        "MenuSelectedFcn", createCallbackFcn(app, @cb_ExportStudentMarkdownClipboard), ...
        "Tooltip", app.tooltips.m_exportStudentMarkdown,"Separator", "on");
    app.m_export_all_txt = uimenu(app.m_export, "Text", "All students (.txt)...", ...
        "MenuSelectedFcn", createCallbackFcn(app, @cb_ExportAll, true), ...
        "Tooltip", app.tooltips.m_exportAlltxt, "UserData", ".txt",...
        "Separator", "on");
    app.m_export_all_pdf = uimenu(app.m_export, "Text", "All students (.pdf)...", ...
        "MenuSelectedFcn", createCallbackFcn(app, @cb_ExportAll, true), ...
        "Tooltip", app.tooltips.m_exportAllpdf, "UserData", ".pdf");

    app.m_about = uimenu(app.fig, "Text", "About");
    app.m_about_version = uimenu(app.m_about, "Text", "Version " + app.version, "Enable", "off");
    app.m_about_help = uimenu(app.m_about, "Text", "Help", "MenuSelectedFcn", createCallbackFcn(app, @cb_gethelp));

end